<br>
<p class="break justify bold">4. Obligaciones de “EL CLIENTE”:</p>
<ul class="b-up-alpha less-li-he justify">
	<li class="one-line-sp">“EL CLIENTE” se obliga incondicionalmente a que la oficina ubicada en {{$contract->office->address}} en {{$contract->office->municipality->name.' '.$contract->office->state->name}} será destinada exclusivamente para oficinas de representación comercial, cualquier otro uso diferente al señalado, causará la rescisión inmediata del presente contrato. el mobiliario y accesorios (escritorios, mesas, sillas, chapas, vidrios, etc.) deberán ser entregados en las mismas condiciones en que fueron recibidos, de lo contrario, “EL CLIENTE” deberá absorber el costo de reparación de los mismos cuando “EL PRESTADOR” se lo solicite.</li>
	<li class="one-line-sp">“EL CLIENTE” acepta pagar de inmediato (i) todos los impuestos sobre ventas, uso, consumo  y cualesquier otros impuestos y derechos de licencia que “EL CLIENTE” tenga que pagar a alguna autoridad gubernamental (y, a petición de “EL PRESTADOR”, “EL CLIENTE” deberá de proporcionar al prestador un comprobante de dicho pago) y (ii) todos los impuestos pagados por “EL PRESTADOR” a alguna autoridad gubernamental que sean atribuibles al uso de la instalación, de ser aplicable, incluyendo, sin limitación, todos los ingresos brutos, impuestos sobre renta y ocupación, impuestos sobre bienes personales tangibles, impuesto de sellos u otros impuestos y aranceles similares.</li>
	<li class="one-line-sp">“EL CLIENTE” se compromete a no fumar dentro de las instalaciones, no introducir animales, combustibles o cualquier otra sustancia que pueda provocar algún percance.</li>
	<li class="one-line-sp">“EL CLIENTE” bajo ninguna circunstancia podrá ceder los derechos de los servicios de oficina que está recibiendo a terceras personas completa ni parcialmente.</li>
	<li class="one-line-sp">Los empleados e invitados de “EL CLIENTE” se comportaran de una manera apropiada para el entorno de negocios; en todo momento deberán de vestirse de manera adecuada para negocios; el nivel de ruido se mantendrá en un nivel adecuado para no interferir con el ambiente de trabajo de los demás y “EL CLIENTE” cumplirá con las directivas de “EL PRESTADOR” con respecto a la seguridad, llaves, estacionamiento, no fumar dentro del establecimiento, así como también no ingerir o introducir bebidas alcohólicas y otros asuntos comunes para todos los ocupantes.</li>
	<li class="one-line-sp">“EL CLIENTE” no podrá realizar negocios en los pasillos, área de recepción o alguna otra área excepto en su oficina designada sin la previa autorización escrita de “EL PRESTADOR”.</li>
	
	<div class="new-page"></div>
	
	<br><br>
	<li class="one-line-sp">“EL CLIENTE” o sus funcionarios, directores, empleados, accionistas, socios, agentes, representantes, contratistas que presenten o incurran en cualquier clase de acoso o comportamiento de índoles hostil, discriminatoria o abusiva, ya sea físico o verbal, hacia los integrantes de “EL PRESTADOR”, otros clientes o sus invitados que se encuentren en el centro de negocios. toda violación de estas reglas se considerará un incumplimiento de su contrato (sin posibilidad de ser subsanado) y, en consecuencia, su contrato podrá ser rescindido de inmediato y los servicios podrán ser suspendidos sin previo aviso.</li>
	<li class="one-line-sp">“EL CLIENTE” está obligado a entregar documentación oficial (IFE-INE, pasaporte o cedula profesional) de cada uno de los empleados que laboren en la ubicación señalada en este contrato por “EL PRESTADOR”.</li>
	<li class="one-line-sp">Queda prohibido para “EL CLIENTE” mantener sonidos o música a alto volumen que pueda molestar a los demás clientes, así mismo, deberá evitarse la permanencia de niños dentro de las instalaciones, en caso contrario, “EL CLIENTE” será responsable de los percances que pudieran provocar ya sea al mobiliario o a los demás clientes de las oficinas.</li>
	<li class="one-line-sp">“EL CLIENTE” se compromete a solicitar autorización a “prestador” previo a realizar cualquier modificación dentro del bien inmueble, aunque sea en beneficio del mismo. cualquier modificación a favor quedará como beneficio para el mismo una vez terminada la vigencia del presente contrato de acuerdo a los artículos 2005 y 2016 del código civil del estado de Jalisco.</li>
	<li class="one-line-sp">“EL CLIENTE” se obliga a conservar el buen estado del inmueble y dar aviso de cualquier situación que pudiera afectar al mismo, de lo contrario se hará responsable de los daños y perjuicios que pudieran ocasionarse por tal motivo.</li>
	<li class="one-line-sp">“EL CLIENTE” acepta expresamente en caso de que diera por rescindido el presente contrato de prestación de servicios por causas imputables al mismo, la penalización será igual a 4 meses de renta, misma que será aplicada a favor de “EL PRESTADOR” para resarcirle de los perjuicios que le causaría el incumplimiento en el plazo del presente contrato, dando aviso a “EL PRESTADOR” con un mínimo de 30 días de anticipación.</li>
</ul>